name: Create Release
on:
  push:
    tags:
      - '*'

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8.0.x'
          distribution: 'zulu'

      - name: Create the (jar) package
        run: mvn --batch-mode package

      - name: Get version
        id: tagName
        run: |
          VERSION=$(cat ./VERSION)
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tagName.outputs.tag }}
          files: |
            ./target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}